# Generated by Django 6.1.1 on 2026-09-23 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_user_site_user_status_application'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='farm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='farms.farm'),
        ),
    ]
