# Generated by Django 6.1.1 on 2026-09-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_farm'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='decline_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
