# Generated by Django 6.1.1 on 2026-09-24 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_application_decline_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_step_secret',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
