# Generated by Django 6.1.1 on 2026-09-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, help_text='For events over more than one day.', null=True)),
                ('time_text', models.CharField(blank=True, help_text='e.g. 12 to 4 p.m.', max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['starts_on'],
            },
        ),
    ]
