# Generated by Django 6.1.1 on 2026-09-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('postal_code', models.CharField(help_text='Like B3H 1G3. The first three characters give the area.', max_length=7)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('could_help', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
