# Generated by Django 6.1.1 on 2026-09-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('drop_date', models.DateField()),
                ('order_cutoff', models.DateTimeField(help_text='Community Managers must order by this time.')),
            ],
            options={
                'ordering': ['-drop_date'],
            },
        ),
    ]
