# Generated by Django 6.1.1 on 2026-09-23 00:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0002_dropcycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drop_date', models.DateField()),
                ('order_cutoff', models.DateTimeField()),
                ('starts_at', models.TimeField(default=datetime.time(11, 0))),
                ('ends_at', models.TimeField(default=datetime.time(13, 0))),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_drops', to='drops.dropcycle')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drops', to='drops.site')),
            ],
            options={
                'ordering': ['drop_date', 'site__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Preorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('bundles', models.PositiveSmallIntegerField(default=1)),
                ('paid', models.BooleanField(default=False)),
                ('picked_up', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site_drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preorders', to='drops.sitedrop')),
            ],
            options={
                'ordering': ['customer_name'],
            },
        ),
        migrations.CreateModel(
            name='DropReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundles_sold', models.PositiveIntegerField()),
                ('bundles_left_over', models.PositiveIntegerField(default=0)),
                ('leftovers_went_to', models.CharField(choices=[('none', 'Nothing left over'), ('donated', 'Donated'), ('kept', 'Kept for the next drop'), ('composted', 'Composted'), ('other', 'Something else')], default='none', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_drop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='drops.sitedrop')),
            ],
        ),
        migrations.CreateModel(
            name='BundleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundles', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('site_drop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='drops.sitedrop')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sitedrop',
            constraint=models.UniqueConstraint(fields=('cycle', 'site'), name='one_drop_per_site_per_cycle'),
        ),
    ]
