# Generated by Django 6.1.1 on 2026-09-23 02:54

from decimal import Decimal
from django.db import migrations, models


def count_old_reports_as_standard(apps, schema_editor):
    # Reports logged before the sliding scale existed only had a total, so count it all as standard-price.
    DropReport = apps.get_model("drops", "DropReport")
    for report in DropReport.objects.filter(bundles_standard=0, bundles_at_cost=0, bundles_free=0):
        report.bundles_standard = report.bundles_sold
        report.save(update_fields=["bundles_standard"])


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0003_sitedrop_preorder_dropreport_bundleorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_price', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Standard / pay-it-forward price for a 10 lb bundle.', max_digits=6)),
                ('at_cost_price', models.DecimalField(decimal_places=2, default=Decimal('7.50'), help_text="At-cost price for people who can't afford the standard price. It's also what a Community Manager owes Square Roots for each paid bundle.", max_digits=6)),
                ('first_drop_cost', models.DecimalField(decimal_places=2, default=Decimal('3.75'), help_text='What a new location owes Square Roots per paid bundle at its very first drop (the first-drop incentive).', max_digits=6)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('1.99'), help_text='Home delivery fee, where delivery is offered.', max_digits=6)),
                ('staging_location', models.CharField(blank=True, help_text='Where farm produce is dropped off and sorted into bundles.', max_length=200)),
            ],
            options={
                'verbose_name_plural': 'operating settings',
            },
        ),
        migrations.AddField(
            model_name='dropreport',
            name='bundles_at_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dropreport',
            name='bundles_free',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dropreport',
            name='bundles_standard',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dropreport',
            name='donations',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='dropreport',
            name='remittance_received_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='delivery',
            field=models.BooleanField(default=False, help_text='Home delivery instead of picking up at the drop.'),
        ),
        migrations.AddField(
            model_name='preorder',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='preorder',
            name='price_tier',
            field=models.CharField(choices=[('standard', 'Standard'), ('at_cost', 'At cost'), ('free', 'Free')], default='standard', max_length=16),
        ),
        migrations.AddField(
            model_name='site',
            name='delivery_partner',
            field=models.CharField(blank=True, help_text='Who does home delivery here, e.g. BayRides.', max_length=100),
        ),
        migrations.AlterField(
            model_name='dropreport',
            name='bundles_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(count_old_reports_as_standard, migrations.RunPython.noop),
    ]
