# Generated by Django 6.1.1 on 2026-09-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0004_operatingsettings_dropreport_bundles_at_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='first_drop_pricing',
            field=models.BooleanField(default=False, help_text="Charge the first-drop price at this location's first drop (for brand-new locations)."),
        ),
    ]
