# Generated by Django 6.1.1 on 2026-09-23 23:06

import django.db.models.deletion
import drops.models
import secrets

from django.db import migrations, models

CHARACTERS = "ACDEFHJKMNPRTUVWXY34679"


def give_existing_preorders_codes(apps, schema_editor):
    Preorder = apps.get_model("drops", "Preorder")
    taken = {}
    for preorder in Preorder.objects.all():
        codes = taken.setdefault(preorder.site_drop_id, set())
        code = ""
        while not code or code in codes:
            code = "".join(secrets.choice(CHARACTERS) for _ in range(4))
        codes.add(code)
        preorder.pickup_code = code
        preorder.save(update_fields=["pickup_code"])



class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0005_site_first_drop_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='preorder',
            name='manage_token',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='preorder',
            name='pickup_code',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='preorder',
            name='source',
            field=models.CharField(choices=[('manager', 'Added by the Community Manager'), ('online', 'Reserved online')], default='manager', max_length=16),
        ),
        migrations.AddField(
            model_name='site',
            name='online_reservations',
            field=models.BooleanField(default=False, help_text='Let customers reserve bundles for this location on the website.'),
        ),
        migrations.AddField(
            model_name='site',
            name='reservation_limit',
            field=models.PositiveIntegerField(default=20, help_text="Bundles set aside for reservations at each drop, online and through the Community Manager. When they're gone, customers can join a waitlist."),
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bundles', models.PositiveSmallIntegerField(default=1)),
                ('price_tier', models.CharField(choices=[('standard', 'Standard'), ('at_cost', 'At cost'), ('free', 'Free')], default='standard', max_length=16)),
                ('delivery', models.BooleanField(default=False)),
                ('delivery_address', models.CharField(blank=True, max_length=200)),
                ('manage_token', models.CharField(db_index=True, default=drops.models.new_manage_token, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site_drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist', to='drops.sitedrop')),
            ],
            options={
                'verbose_name_plural': 'waitlist entries',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.RunPython(give_existing_preorders_codes, migrations.RunPython.noop),
    ]
