# Generated by Django 6.1.1 on 2026-09-23 23:39

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0006_online_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='pay_it_forward',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='pay_it_forward',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.CreateModel(
            name='StandingReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bundles', models.PositiveSmallIntegerField(default=1)),
                ('price_tier', models.CharField(choices=[('standard', 'Standard'), ('at_cost', 'At cost'), ('free', 'Free')], default='standard', max_length=16)),
                ('pay_it_forward', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('delivery', models.BooleanField(default=False)),
                ('delivery_address', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standing_reservations', to='drops.site')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='preorder',
            name='standing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preorders', to='drops.standingreservation'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='standing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='drops.standingreservation'),
        ),
    ]
