# Generated by Django 6.1.1 on 2026-09-23 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0007_pay_it_forward_and_every_drop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='preorder',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='standingreservation',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français')], default='en', max_length=5),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='source',
            field=models.CharField(choices=[('manager', 'Added by the Community Manager'), ('online', 'Reserved online'), ('host', 'Reserved by the host site')], default='manager', max_length=16),
        ),
    ]
