# Generated by Django 6.1.1 on 2026-09-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0008_languages_and_host_reservations'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitedrop',
            name='order_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
