# Generated by Django 6.1.1 on 2026-09-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0009_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='feedback',
            field=models.CharField(blank=True, choices=[('good', 'Great'), ('okay', 'Okay'), ('poor', 'Not great')], max_length=8),
        ),
        migrations.AddField(
            model_name='preorder',
            name='feedback_asked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='preorder',
            name='feedback_comment',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
