# Generated by Django 6.1.1 on 2026-10-01 01:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0010_feedback'),
        ('farms', '0004_routes_and_drop_off_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='DropOffPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hub_share_percent', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text="What the hub gets for sorting, as a percent of what's bought from the supplier below (e.g. 10).", max_digits=5)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('hub_share_supplier', models.ForeignKey(blank=True, help_text="Whose orders the hub's share is worked out from (e.g. Ketty Brow's).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='farms.farm')),
                ('hub_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hubs_run', to='drops.site')),
            ],
            options={
                'ordering': ['route__sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='site',
            name='drop_off',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='drops.dropoffpoint'),
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, help_text='e.g. North of Halifax and Truro', max_length=200)),
                ('form_sent_on', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='When the order form goes out.')),
                ('orders_due_on', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text="When locations' orders are due.")),
                ('trucks_on', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='When the trucks deliver.')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('shares_form_with', models.ForeignKey(blank=True, help_text='Uses the same order form as this route.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='drops.route')),
                ('suppliers', models.ManyToManyField(blank=True, help_text='Who this route buys from.', related_name='routes', to='farms.farm')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='dropoffpoint',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_off_points', to='drops.route'),
        ),
        migrations.AddField(
            model_name='site',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='drops.route'),
        ),
    ]
