# Generated by Django 6.1.1 on 2026-10-01 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0011_routes_and_drop_off_points'),
        ('ordering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='transport',
            field=models.ForeignKey(blank=True, help_text="Who drives this route's trucks.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='ordering.transportcompany'),
        ),
        migrations.AddField(
            model_name='route',
            name='uses_order_forms',
            field=models.BooleanField(default=False),
        ),
    ]
