"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Running on your own computer, nothing needs setting. When the site is hosted, these come from
# environment variables (see HOSTING.md):
#   DJANGO_DEBUG=0                     production mode
#   DJANGO_SECRET_KEY=...              a long random secret, never in git
#   DJANGO_ALLOWED_HOSTS=squarerootssmu.ca,www.squarerootssmu.ca
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if not DEBUG:
        raise RuntimeError('Set DJANGO_SECRET_KEY before running in production (see HOSTING.md).')
    SECRET_KEY = 'django-insecure-only-for-local-development'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]
# The browser's address has to be trusted for logins and forms to work over HTTPS.
CSRF_TRUSTED_ORIGINS = [f'https://{host}' for host in ALLOWED_HOSTS if host not in ('localhost', '127.0.0.1')]

# The React dev server (Vite) forwards /api here, so requests arrive as
# localhost:<vite port> and Django treats them as same-origin.

if not DEBUG:
    # Only send cookies over HTTPS, and tell browsers to always use HTTPS.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = os.environ.get('DJANGO_SSL_REDIRECT', '1') == '1'
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30
    # Most hosts sit behind a proxy that handles HTTPS and says so in this header.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'accounts',
    'drops',
    'farms',
    'website',
    'data_import',
    'ordering',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves the built website (frontend/dist) and Django's own files when hosted. See HOSTING.md.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Our own user model adds a `role` field (admin, community manager, farm, host site).
AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    # Log in once with a normal Django session; the browser keeps the cookie.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'EXCEPTION_HANDLER': 'config.exceptions.api_exception_handler',
    # Public forms that anyone can send are limited per visitor, to stop spam and password guessing.
    'DEFAULT_THROTTLE_RATES': {
        'reservations': '30/hour',
        'login': '20/minute',
        'signup': '10/hour',
        'contact': '10/hour',
        'password_reset': '5/hour',
    },
}

# Demo mode shows the demo accounts on the login page and labels the made-up data.
# Turn it off for real use:  DEMO_MODE=0 python manage.py runserver
DEMO_MODE = os.environ.get('DEMO_MODE', '1') == '1'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# The demo uses db.sqlite3. Keep real Square Roots data in its own file so the two never mix:
#   DATABASE_PATH=real.sqlite3 DEMO_MODE=0 python manage.py runserver
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / os.environ.get('DATABASE_PATH', 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-ca'

TIME_ZONE = 'America/Halifax'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # `manage.py collectstatic` puts Django's own files here

# When hosted, Django also serves the React website: build it with `npm run build` in frontend/,
# and every file in frontend/dist is served at the site's root (see config/urls.py for the pages).
FRONTEND_DIST = BASE_DIR.parent / 'frontend' / 'dist'
WHITENOISE_ROOT = FRONTEND_DIST if FRONTEND_DIST.exists() else None
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage'},
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Locally, emails are printed in the runserver terminal as readable text (see accounts/email_backend.py).
# To send real email, set EMAIL_HOST and the rest from your email provider (see HOSTING.md).
DEFAULT_FROM_EMAIL = 'Square Roots <squareroots@enactussmu.ca>'
TEAM_EMAIL = 'squareroots@enactussmu.ca'  # where sign-up and contact notifications go

# How long personal details are kept (see the Privacy page and `manage.py forget_old_details`).
CUSTOMER_DETAILS_KEPT_DAYS = 60   # after a customer's drop
CONTACT_MESSAGES_KEPT_DAYS = 365  # Contact Us messages

if os.environ.get('EMAIL_HOST'):
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
            'OPTIONS': {
                'host': os.environ['EMAIL_HOST'],
                'port': int(os.environ.get('EMAIL_PORT', '587')),
                'username': os.environ.get('EMAIL_USER', ''),
                'password': os.environ.get('EMAIL_PASSWORD', ''),
                'use_tls': True,
                'timeout': 20,
            },
        },
    }
    DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_FROM', DEFAULT_FROM_EMAIL)
else:
    MAILERS = {
        'default': {
            'BACKEND': 'accounts.email_backend.ReadableConsoleBackend',
        },
    }

# Errors on the hosted site are written to the host's log (the terminal running gunicorn).
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['console'], 'level': 'WARNING'},
}


# Tests don't share a cache, so request limits from one test never affect another.
# (Tests of the limits themselves switch a real cache back on.)
if len(sys.argv) > 1 and sys.argv[1] == 'test':
    CACHES = {'default': {'BACKEND': 'django.core.cache.backends.dummy.DummyCache'}}
