# Generated by Django 6.1.1 on 2026-10-01 01:45

import django.db.models.deletion
import django.utils.timezone
import ordering.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drops', '0011_routes_and_drop_off_points'),
        ('farms', '0005_farm_contact_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=120)),
                ('box_size', models.CharField(blank=True, help_text='e.g. 50 lb box, case of 24', max_length=60)),
                ('price', models.DecimalField(decimal_places=2, help_text='Per box', max_digits=8)),
                ('available', models.PositiveIntegerField(blank=True, help_text='Boxes available; blank if no limit given', null=True)),
                ('notes', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['product'],
            },
        ),
        migrations.CreateModel(
            name='TransportCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('contact_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'transport companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrderForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(help_text='When the trucks deliver.')),
                ('orders_due', models.DateTimeField(help_text="When locations' orders are due.")),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for orders'), ('sent', 'Sent to suppliers')], default='draft', max_length=8)),
                ('notes', models.TextField(blank=True, help_text='Shown to locations at the top of the form.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_forms', to='drops.dropcycle')),
                ('routes', models.ManyToManyField(related_name='order_forms', to='drops.route')),
            ],
            options={
                'ordering': ['-delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='LocationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_orders', to='drops.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_orders', to='ordering.orderform')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFormItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=120)),
                ('box_size', models.CharField(blank=True, max_length=60)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('available', models.PositiveIntegerField(blank=True, null=True)),
                ('deal', models.CharField(blank=True, choices=[('', 'No note'), ('good', 'Good deal'), ('pricey', 'Pricier than usual')], default='', max_length=8)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordering.orderform')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='farms.farm')),
                ('price_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ordering.priceitem')),
            ],
            options={
                'ordering': ['sort_order', 'product'],
            },
        ),
        migrations.CreateModel(
            name='LocationOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxes', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ordering.locationorder')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='ordering.orderformitem')),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_on', models.DateField(default=django.utils.timezone.localdate)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='drops.dropcycle')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_lists', to='farms.farm')),
            ],
            options={
                'ordering': ['-cycle__drop_date', 'supplier__name'],
            },
        ),
        migrations.AddField(
            model_name='priceitem',
            name='price_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ordering.pricelist'),
        ),
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('supplier', 'Supplier order'), ('transport', 'Transport run')], max_length=10)),
                ('token', models.CharField(default=ordering.models.new_token, max_length=40, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('confirmed', 'Confirmed'), ('cant', "Can't do it")], default='waiting', max_length=10)),
                ('reply', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='drops.route')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='farms.farm')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='ordering.orderform')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ordering.transportcompany')),
            ],
            options={
                'ordering': ['kind', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='locationorder',
            constraint=models.UniqueConstraint(fields=('form', 'site'), name='one_order_per_site_per_form'),
        ),
        migrations.AddConstraint(
            model_name='locationorderline',
            constraint=models.UniqueConstraint(fields=('order', 'item'), name='one_line_per_item'),
        ),
        migrations.AddConstraint(
            model_name='pricelist',
            constraint=models.UniqueConstraint(fields=('supplier', 'cycle'), name='one_price_list_per_supplier_per_cycle'),
        ),
    ]
