// Words for the public website (menus, pages, forms), in English and French.
// The customer reservation words are in i18n.jsx; both are used through `const { t } = useLanguage()`,
// for example t.nav.about. The main page text the team can edit is in siteText.jsx.
//
// Keep both languages in step: test/i18n.test.js fails if a word is missing from one of them.
// The French was written for this prototype; have a French speaker check it before real use.

export const SITE_WORDS = {
  en: {
    common: {
      optional: 'optional',
      sending: 'Sending…',
      loading: 'Loading…',
      privacy: 'Privacy',
      logIn: 'Log in',
      signUp: 'Sign up',
      email: 'Email',
      pleaseFill: 'Please fill this in.',
    },
    roles: {
      admin: 'Admin',
      community_manager: 'Community Manager',
      farm: 'Farm',
      host_site: 'Host Site',
    },
    titles: {
      '/': 'Home',
      '/about': 'About',
      '/drop-dates-locations': 'Drop Dates & Locations',
      '/for-farms': 'For Farms',
      '/become-a-community-manager': 'Become a Community Manager',
      '/events': 'Events',
      '/contact-us': 'Contact Us',
      '/reserve': 'Reserve a Bundle',
      '/whats-in-the-bundle': 'What’s in the Bundle',
      '/privacy': 'Privacy',
      '/request-a-location': 'Bring Square Roots to Your Area',
      '/signup': 'Partner Sign-up',
      '/portal/login': 'Log in',
      '/portal/pending': 'Application received',
      '/portal/forgot-password': 'Forgot password',
      '/portal/reset-password': 'Choose a new password',
      signupRole: 'Partner Sign-up',
      yourReservation: 'Your Reservation',
      notFound: 'Page not found',
      portalSuffix: ' Partner Portal',
    },
    nav: {
      logoAlt: 'Square Roots home',
      skipToContent: 'Skip to main content',
      menu: 'Menu',
      main: 'Main',
      about: 'About',
      dropDates: 'Drop Dates & Locations',
      getInvolved: 'Get Involved',
      forFarms: 'For Farms',
      becomeCm: 'Become a Community Manager',
      hostDrop: 'Host a Drop',
      partnerSignup: 'Partner Sign-up',
      events: 'Events',
      contactUs: 'Contact Us',
      reserve: 'Reserve a Bundle',
      partnerPortal: 'Partner Portal',
    },
    footer: {
      enactusAlt: "Enactus Saint Mary's University",
      website: 'Website',
      contactUs: 'Contact Us',
      partnerPortal: 'Partner Portal',
    },
    partnerBand: {
      title: 'Partner Portal',
      text: 'Community Managers, farms and host sites use the partner portal to order bundles, post produce and see drop dates, all in one place.',
    },
    partners: {
      title: 'Our Partners & Supporters',
      novaScotiaAlt: 'Government of Nova Scotia',
      saintMarysAlt: "Saint Mary's University",
    },
    photos: {
      boxes: 'Boxes of apples, carrots and potatoes',
      parsnips: 'Boxes of parsnips, carrots and sweet potatoes',
      bag: 'A Square Roots bag with apples, cucumbers and corn',
      bagFull: 'A Square Roots bag filled with apples, cucumbers, corn and potatoes',
      marketPotatoes: 'Potatoes and beets at a Square Roots market',
      marketPotatoesForSale: 'Potatoes and beets for sale at a Square Roots market',
      secondsPotatoes: 'Seconds potatoes and beets ready to sell',
      field: 'Rows of leafy greens on a farm',
      shirt: 'A volunteer in an “All my friends hate food waste” shirt beside boxes of carrots',
      team: 'Four Square Roots team members in matching shirts, facing away',
      evan: 'Evan Payne with his family',
    },
    home: {
      getInvolved: 'Get Involved',
      aboutUs: 'About Us',
      mission: 'Mission',
      impact: 'Impact',
      support: 'Support',
      dropDates: 'Drop Dates & Locations',
      enactusTitle: "Enactus Saint Mary's",
      learnMore: 'Learn More',
      getInvolvedLinks: 'Get involved',
      contactUs: 'Contact Us',
      forFarms: 'For Farms',
      becomeCm: 'Become a Community Manager',
      hostDrop: 'Host a Drop',
    },
    aboutPage: {
      title: 'About Us',
      howItWorks: 'How It Works',
      findCommunity: 'Find a community near you:',
      dropDates: 'Drop Dates & Locations',
      communityManagers: 'Community Managers',
      becomeCm: 'Become a Community Manager',
      leadership: 'Our Leadership',
      evanRole: 'President, Enactus Saint Mary’s',
      evan1:
        'As President of Enactus Saint Mary’s, the student team behind Square Roots, Evan plays a leading role in guiding the project and the people who make it happen. He studies business at Saint Mary’s University’s Sobey School of Business.',
      evan2:
        'Evan has worked as a student assistant at the university’s Arthur L. Irving Entrepreneurship Centre. His experience includes growth initiatives, team training and project coordination, with community and economic development programs across Nova Scotia.',
      evan3:
        'He brings that experience to Square Roots’ mission: making sure good food doesn’t go to waste while people go without, supporting local farms, and helping Community Managers build something of their own.',
    },
    locationsPage: {
      title: 'Locations',
      becomeCm: 'Become a Community Manager',
      dropDates: (year) => `${year} Drop Dates`,
      nextDrop: (date) => `Next drop: ${date}`,
      and: '&',
      payWhatWorks: 'Pay what works for you',
      bundleSize: 'Every bundle is 10 lbs of fresh local produce.',
      payItForward: 'Pay it forward: helps cover bundles for neighbours who need them',
      atCost: 'At cost, if money is tight',
      free: 'Free',
      freeText: 'If money is too tight right now',
      reserve: 'Reserve a bundle',
      delivery: (places, fee) => `Home delivery is available ${places} for ${fee}.`,
      deliveryPlace: (site, partner) => `in ${site} with ${partner}`,
      findLocation: 'Find a Location',
      loading: 'Loading locations…',
      nextDropLabel: 'Next drop:',
      comingSoon: 'Next drop date coming soon',
      reserveAt: (site) => `Reserve at ${site}`,
      onInstagram: (site) => `${site} on Instagram`,
      onFacebook: (site) => `${site} on Facebook`,
      directions: 'Directions',
      highlights: 'Location Highlights',
      noneNearTitle: 'Don’t see a location near you?',
      noneNearText:
        "Start one as a Community Manager, or offer a space in your community where drops can happen. We'll help with the rest.",
      startLocation: 'Start a location',
      hostDrop: 'Host a Drop',
      askForOne: 'Ask for one near you',
    },
    farms: {
      title: 'For Farms',
      interested: 'Interested?',
    },
    cm: {
      become: 'Become a Community Manager',
    },
    events: {
      title: 'Events',
      noneTitle: 'No upcoming events right now',
      noneText: 'Follow us for giveaways, markets and pop-ups. Regular drops happen every two weeks at our ',
      locations: 'locations',
      past: 'Past events',
      to: 'to',
      hostTitle: 'Want to host an event with us?',
      hostText: "Community centres, schools and organizations can host a Square Roots drop. Sign up and we'll get in touch.",
    },
    contact: {
      title: 'Contact Us',
      workTogether: 'Let’s Work Together',
      getInTouch: 'Get in touch.',
      partnerNote: 'Want to become a Community Manager, sell us your produce or host a drop? ',
      partnerLink: 'Sign up as a partner',
      thanks: 'Thanks for submitting!',
      firstName: 'First Name',
      lastName: 'Last Name',
      email: 'Email',
      message: 'Message',
      send: 'Send',
      keepFor: 'We keep messages for one year.',
    },
    signup: {
      chooserTitle: 'Join Square Roots',
      chooserLead:
        'Sign up for the partner portal. Tell us a little about yourself, and once the Square Roots team approves your account you can start ordering, posting produce or scheduling drops.',
      whichDescribesYou: 'Which describes you?',
      haveAccount: 'Already have an account? ',
      logInToPortal: 'Log in to the partner portal',
      breadcrumb: 'Partner sign-up',
      roles: {
        'community-manager': {
          label: 'Community Manager',
          title: 'Become a Community Manager',
          summary:
            'Run a Square Roots location in your community. Order produce bi-weekly and sell affordable bundles. Any revenue above the produce cost and our commission is yours.',
          button: 'Apply to run a location',
        },
        farm: {
          label: 'Farm',
          title: 'Sell Us Your Seconds',
          summary:
            'Earn from produce that would otherwise be reploughed or sent to landfill. We order about 24 times a year, generally bi-weekly.',
          button: 'Sign up as a farm',
        },
        'host-site': {
          label: 'Host Site',
          title: 'Host a Drop',
          summary:
            'Have a community centre, church hall, school or other space? Host a Square Roots drop and help your neighbours get affordable produce.',
          button: 'Offer your space',
        },
      },
      fixBoxes: 'Please fix the highlighted boxes below.',
      firstName: 'First name',
      lastName: 'Last name',
      email: 'Email',
      phone: 'Phone',
      whereRun: 'Where would you like to run drops?',
      chooseLocation: 'Choose a location…',
      somewhereNew: 'Somewhere new',
      plannedLocation: 'Planned location',
      townOrNeighbourhood: 'Town or neighbourhood',
      farmName: 'Farm name',
      whereFarm: 'Where is your farm?',
      townOrCounty: 'Town or county',
      produceTypes: 'What types of produce do you sell?',
      pounds: 'How many pounds do you have available on a bi-weekly basis?',
      orgName: 'Name of your organization or space',
      spaceAddress: 'Address of your space',
      alreadyHost: 'Do you already host a Square Roots location?',
      newLocation: 'No, this would be a new location',
      yesSite: (site) => `Yes: ${site}`,
      message: 'Message',
      optional: 'Optional',
      loginLegend: 'Your partner portal login',
      username: 'Username',
      password: 'Password',
      passwordHint: 'At least 8 characters, and not just numbers',
      review: "We'll review your application and email you when your account is approved. Already have an account? ",
      howWeUse: '. How we use your details: ',
    },
    requestLocation: {
      title: 'Bring Square Roots to Your Area',
      lead: 'No location near you yet? Tell us where you are. When enough people ask, we look for someone to start one.',
      thanks: (area) => `Thank you! We’ve added ${area} to the list and we’ll email you if a location opens nearby. `,
      couldHelpThanks: 'Since you said you could help, someone from the team will be in touch. ',
      seeLocations: 'See current locations',
      postalCode: 'Postal code',
      postalHint: '(or just the first part, like B3H)',
      town: 'Town or neighbourhood',
      email: 'Email',
      emailHint: '(so we can tell you if a location opens)',
      couldHelp: 'I could help run or host a location',
      couldHelpHint: ' Community Managers run drops every two weeks, with support from our team.',
      anythingElse: 'Anything else?',
      ask: 'Ask for a location',
      keepOnly: 'We keep your email and postal code only for this.',
    },
    privacyPage: {
      title: 'Privacy',
      lead: 'What we collect, why, who sees it, and how long we keep it.',
      draft:
        'This is a draft for Square Roots to review before the website is used by the public, ideally with advice from someone who knows Canadian privacy law (PIPEDA).',
      whoTitle: 'Who we are',
      who: 'Square Roots is a community interest company run by students from Enactus Saint Mary’s, at Saint Mary’s University in Halifax. Questions about your information go to ',
      reserveTitle: 'When you reserve a bundle',
      weAsk: 'We ask for:',
      askName: 'your name, so your Community Manager knows who the bundle is for;',
      askContact: 'an email or phone number, so we can send your confirmation and tell you if plans change;',
      askAddress: 'your address, only if you ask for home delivery.',
      alsoKeep:
        'We also keep how many bundles you reserved, the price you chose and any gift you added. The price you choose is private: only your Community Manager and the Square Roots team see it.',
      whoSeesLabel: 'Who sees it:',
      whoSees:
        ' your location’s Community Manager and the Square Roots team. For home delivery, the delivery partner (for example BayRides) gets your name, address and phone number. If a host site reserved for you, they see the name they gave and your pickup code. We never sell your information or use it for advertising.',
      howLongLabel: 'How long:',
      howLong:
        ' we remove your name and contact details 60 days after your drop. If you cancel, they’re deleted right away. If you asked us to reserve at every drop, we keep your details until you stop.',
      emailsTitle: 'Emails we send',
      emails:
        'Only about your reservations: your confirmation, reminders before your drop, a short question afterwards about how your bundle was, and notices if your drop changes. There’s no mailing list.',
      areaTitle: '“Bring Square Roots to my area”',
      area: 'If you ask us to start a location near you, we keep your email and postal code to tell you if one opens, and to show the team where people are asking. You can ask us to delete it at any time.',
      contactTitle: 'Contact Us messages',
      contact: 'We keep messages sent through the Contact Us page for one year, then delete them.',
      accountsTitle: 'Partner portal accounts',
      accounts:
        'Community Managers, farms and host sites have accounts with their name, email, phone and organization. These are kept while they work with Square Roots. Ask us to close your account and we’ll delete it.',
      cookiesTitle: 'Cookies and your device',
      cookies:
        'The partner portal uses one cookie to keep you logged in. If you tick “Remember my details” when reserving, your name and contact details are saved on your own device (not on our servers) so you don’t have to type them again. The website doesn’t use tracking or advertising cookies.',
      choicesTitle: 'Your choices',
      choices:
        'You can see, correct or delete your information at any time: change or cancel a reservation from the link in your confirmation email, or email ',
      choicesEnd: ' and we’ll help within 30 days.',
      back: 'Back to reserving a bundle',
    },
    login: {
      title: 'Partner Portal',
      lead: 'For Community Managers, farms, host sites and the Square Roots team.',
      sessionEnded: "You were logged out because you hadn't used the portal for a while. Please log in again.",
      username: 'Username',
      password: 'Password',
      code: '6-digit code',
      codeHint: '(from your authenticator app)',
      loggingIn: 'Logging in…',
      logIn: 'Log in',
      forgot: 'Forgot your password?',
      newHere: 'New to Square Roots? ',
      signUp: 'Sign up as a partner',
      sideTitle: 'Reducing Food Waste, Increasing Food Security',
      sideText:
        "Square Roots connects perfectly healthy produce that doesn't meet grocery store cosmetic standards with community members across Nova Scotia.",
      demoTitle: 'Demo accounts',
      demoMode: 'Demo mode.',
      demoNote: ' These accounts and their data are made up. This list disappears when demo mode is turned off.',
      demoTap: 'Tap an account to fill in the form. Every demo password is ',
      demoPending: 'Signed up, waiting for approval',
      demoPendingNote: 'These people signed up on the website. Log in as one to see what they see.',
    },
    pending: {
      declinedTitle: 'About your application',
      thanks: (name) => `Thanks, ${name}!`,
      declined:
        "We're not able to approve your application right now. If you have questions, please email us at squareroots@enactussmu.ca.",
      received: (role) => `We've received your application to join Square Roots as a ${role}.`,
      nextTitle: 'What happens next',
      next1: "Someone from the Square Roots team at Enactus Saint Mary's reviews your application.",
      next2: "We'll email you once your account is approved. This usually takes a few days.",
      next3: 'Then log in here with the username and password you chose, and your partner portal will be ready.',
      back: 'Back to the Square Roots site',
      logOut: 'Log out',
    },
    forgot: {
      title: 'Forgot your password?',
      lead: "Enter the email address on your partner portal account and we'll send you a link to choose a new one.",
      enterEmail: 'Enter the email address on your account.',
      linkOnce: 'The link works once. The email also reminds you of your username. If nothing arrives in a few minutes, check your spam folder or email us at ',
      backToLogin: 'Back to log in',
      emailMe: 'Email me a link',
    },
    reset: {
      title: 'Choose a new password',
      noMatch: "The two passwords don't match.",
      changed: 'Your password is changed. You can log in now as ',
      logIn: 'Log in',
      newLink: 'Get a new link',
      newPassword: 'New password',
      passwordHint: '(at least 8 characters, and not just numbers)',
      again: 'Type it again',
      saving: 'Saving…',
      save: 'Save new password',
    },
    notFound: {
      title: 'Page not found',
      text: "We couldn't find that page. It may have moved, or the link may have a typo.",
      home: 'Go to the home page',
      findDrop: 'Find a drop near you',
      portal: 'Partner Portal',
    },
    crash: {
      title: 'Something went wrong',
      sorry: 'Sorry, this page didn’t load properly.',
      tryAgain: 'Try loading the page again. If it keeps happening, please let us know at squareroots@enactussmu.ca.',
      reload: 'Load the page again',
      home: 'Go to the home page',
    },
  },

  fr: {
    common: {
      optional: 'facultatif',
      sending: 'Envoi…',
      loading: 'Chargement…',
      privacy: 'Confidentialité',
      logIn: 'Se connecter',
      signUp: 'S’inscrire',
      email: 'Courriel',
      pleaseFill: 'Veuillez remplir ce champ.',
    },
    roles: {
      admin: 'Administrateur',
      community_manager: 'Gestionnaire communautaire',
      farm: 'Ferme',
      host_site: 'Site d’accueil',
    },
    titles: {
      '/': 'Accueil',
      '/about': 'À propos',
      '/drop-dates-locations': 'Dates et lieux',
      '/for-farms': 'Pour les fermes',
      '/become-a-community-manager': 'Devenir gestionnaire communautaire',
      '/events': 'Événements',
      '/contact-us': 'Nous joindre',
      '/reserve': 'Réserver un panier',
      '/whats-in-the-bundle': 'Dans le panier',
      '/privacy': 'Confidentialité',
      '/request-a-location': 'Square Roots dans votre région',
      '/signup': 'Inscription des partenaires',
      '/portal/login': 'Connexion',
      '/portal/pending': 'Demande reçue',
      '/portal/forgot-password': 'Mot de passe oublié',
      '/portal/reset-password': 'Nouveau mot de passe',
      signupRole: 'Inscription des partenaires',
      yourReservation: 'Votre réservation',
      notFound: 'Page introuvable',
      portalSuffix: ' – Portail des partenaires',
    },
    nav: {
      logoAlt: 'Accueil Square Roots',
      skipToContent: 'Passer au contenu principal',
      menu: 'Menu',
      main: 'Principal',
      about: 'À propos',
      dropDates: 'Dates et lieux',
      getInvolved: 'Participer',
      forFarms: 'Pour les fermes',
      becomeCm: 'Devenir gestionnaire communautaire',
      hostDrop: 'Accueillir une distribution',
      partnerSignup: 'Inscription des partenaires',
      events: 'Événements',
      contactUs: 'Nous joindre',
      reserve: 'Réserver un panier',
      partnerPortal: 'Portail des partenaires',
    },
    footer: {
      enactusAlt: 'Enactus Université Saint Mary’s',
      website: 'Site Web',
      contactUs: 'Nous joindre',
      partnerPortal: 'Portail des partenaires',
    },
    partnerBand: {
      title: 'Portail des partenaires',
      text: 'Les gestionnaires communautaires, les fermes et les sites d’accueil utilisent le portail pour commander des paniers, afficher leurs produits et voir les dates de distribution, au même endroit.',
    },
    partners: {
      title: 'Nos partenaires et commanditaires',
      novaScotiaAlt: 'Gouvernement de la Nouvelle-Écosse',
      saintMarysAlt: 'Université Saint Mary’s',
    },
    photos: {
      boxes: 'Des boîtes de pommes, de carottes et de pommes de terre',
      parsnips: 'Des boîtes de panais, de carottes et de patates douces',
      bag: 'Un sac Square Roots avec des pommes, des concombres et du maïs',
      bagFull: 'Un sac Square Roots rempli de pommes, de concombres, de maïs et de pommes de terre',
      marketPotatoes: 'Des pommes de terre et des betteraves à un marché Square Roots',
      marketPotatoesForSale: 'Des pommes de terre et des betteraves en vente à un marché Square Roots',
      secondsPotatoes: 'Des pommes de terre et des betteraves déclassées, prêtes à vendre',
      field: 'Des rangs de légumes-feuilles dans une ferme',
      shirt: 'Une bénévole en t-shirt « All my friends hate food waste » à côté de boîtes de carottes',
      team: 'Quatre membres de l’équipe Square Roots en t-shirts assortis, de dos',
      evan: 'Evan Payne avec sa famille',
    },
    home: {
      getInvolved: 'Participer',
      aboutUs: 'À propos',
      mission: 'Mission',
      impact: 'Impact',
      support: 'Soutien',
      dropDates: 'Dates et lieux',
      enactusTitle: 'Enactus Saint Mary’s',
      learnMore: 'En savoir plus',
      getInvolvedLinks: 'Participer',
      contactUs: 'Nous joindre',
      forFarms: 'Pour les fermes',
      becomeCm: 'Devenir gestionnaire communautaire',
      hostDrop: 'Accueillir une distribution',
    },
    aboutPage: {
      title: 'À propos',
      howItWorks: 'Comment ça fonctionne',
      findCommunity: 'Trouvez une communauté près de chez vous :',
      dropDates: 'Dates et lieux',
      communityManagers: 'Gestionnaires communautaires',
      becomeCm: 'Devenir gestionnaire communautaire',
      leadership: 'Notre direction',
      evanRole: 'Président, Enactus Saint Mary’s',
      evan1:
        'Président d’Enactus Saint Mary’s, l’équipe étudiante derrière Square Roots, Evan joue un rôle de premier plan dans l’orientation du projet et des personnes qui le font vivre. Il étudie en administration des affaires à la Sobey School of Business de l’Université Saint Mary’s.',
      evan2:
        'Evan a été assistant étudiant au Arthur L. Irving Entrepreneurship Centre de l’université. Son expérience comprend des projets de croissance, la formation d’équipes et la coordination de projets, au sein de programmes de développement communautaire et économique partout en Nouvelle-Écosse.',
      evan3:
        'Il met cette expérience au service de la mission de Square Roots : éviter que de la bonne nourriture soit gaspillée pendant que des gens en manquent, soutenir les fermes locales et aider les gestionnaires communautaires à bâtir leur propre projet.',
    },
    locationsPage: {
      title: 'Lieux',
      becomeCm: 'Devenir gestionnaire communautaire',
      dropDates: (year) => `Dates de distribution ${year}`,
      nextDrop: (date) => `Prochaine distribution : ${date}`,
      and: 'et',
      payWhatWorks: 'Payez selon vos moyens',
      bundleSize: 'Chaque panier contient 10 lb de produits frais d’ici.',
      payItForward: 'Donner au suivant : aide à offrir des paniers aux voisins qui en ont besoin',
      atCost: 'Prix coûtant, si votre budget est serré',
      free: 'Gratuit',
      freeText: 'Si votre budget est trop serré en ce moment',
      reserve: 'Réserver un panier',
      delivery: (places, fee) => `La livraison à domicile est offerte ${places} pour ${fee}.`,
      deliveryPlace: (site, partner) => `à ${site} avec ${partner}`,
      findLocation: 'Trouver un lieu',
      loading: 'Chargement des lieux…',
      nextDropLabel: 'Prochaine distribution :',
      comingSoon: 'Prochaine date à venir',
      reserveAt: (site) => `Réserver à ${site}`,
      onInstagram: (site) => `${site} sur Instagram`,
      onFacebook: (site) => `${site} sur Facebook`,
      directions: 'Itinéraire',
      highlights: 'Nos lieux en vedette',
      noneNearTitle: 'Aucun lieu près de chez vous?',
      noneNearText:
        'Lancez-en un comme gestionnaire communautaire, ou offrez un espace dans votre communauté pour accueillir les distributions. Nous vous aiderons pour le reste.',
      startLocation: 'Lancer un lieu',
      hostDrop: 'Accueillir une distribution',
      askForOne: 'En demander un près de chez vous',
    },
    farms: {
      title: 'Pour les fermes',
      interested: 'Intéressé?',
    },
    cm: {
      become: 'Devenir gestionnaire communautaire',
    },
    events: {
      title: 'Événements',
      noneTitle: 'Aucun événement à venir pour le moment',
      noneText:
        'Suivez-nous pour les distributions gratuites, les marchés et les kiosques éphémères. Les distributions régulières ont lieu toutes les deux semaines dans nos ',
      locations: 'lieux',
      past: 'Événements passés',
      to: 'au',
      hostTitle: 'Vous aimeriez organiser un événement avec nous?',
      hostText:
        'Les centres communautaires, les écoles et les organismes peuvent accueillir une distribution Square Roots. Inscrivez-vous et nous vous contacterons.',
    },
    contact: {
      title: 'Nous joindre',
      workTogether: 'Travaillons ensemble',
      getInTouch: 'Écrivez-nous.',
      partnerNote: 'Vous voulez devenir gestionnaire communautaire, nous vendre vos produits ou accueillir une distribution? ',
      partnerLink: 'Inscrivez-vous comme partenaire',
      thanks: 'Merci pour votre message!',
      firstName: 'Prénom',
      lastName: 'Nom',
      email: 'Courriel',
      message: 'Message',
      send: 'Envoyer',
      keepFor: 'Nous gardons les messages pendant un an.',
    },
    signup: {
      chooserTitle: 'Joignez-vous à Square Roots',
      chooserLead:
        'Inscrivez-vous au portail des partenaires. Parlez-nous un peu de vous : une fois votre compte approuvé par l’équipe de Square Roots, vous pourrez commander, afficher vos produits ou planifier des distributions.',
      whichDescribesYou: 'Qu’est-ce qui vous décrit le mieux?',
      haveAccount: 'Vous avez déjà un compte? ',
      logInToPortal: 'Connectez-vous au portail des partenaires',
      breadcrumb: 'Inscription des partenaires',
      roles: {
        'community-manager': {
          label: 'Gestionnaire communautaire',
          title: 'Devenir gestionnaire communautaire',
          summary:
            'Gérez un lieu Square Roots dans votre communauté. Commandez des produits toutes les deux semaines et vendez des paniers abordables. Tout revenu au-delà du coût des produits et de notre commission vous revient.',
          button: 'Proposer de gérer un lieu',
        },
        farm: {
          label: 'Ferme',
          title: 'Vendez-nous vos produits déclassés',
          summary:
            'Tirez un revenu de produits qui seraient autrement enfouis dans les champs ou envoyés au dépotoir. Nous commandons environ 24 fois par année, généralement toutes les deux semaines.',
          button: 'Inscrire ma ferme',
        },
        'host-site': {
          label: 'Site d’accueil',
          title: 'Accueillir une distribution',
          summary:
            'Vous avez un centre communautaire, une salle paroissiale, une école ou un autre espace? Accueillez une distribution Square Roots et aidez vos voisins à se procurer des produits abordables.',
          button: 'Offrir votre espace',
        },
      },
      fixBoxes: 'Veuillez corriger les champs en surbrillance ci-dessous.',
      firstName: 'Prénom',
      lastName: 'Nom',
      email: 'Courriel',
      phone: 'Téléphone',
      whereRun: 'Où aimeriez-vous organiser des distributions?',
      chooseLocation: 'Choisissez un lieu…',
      somewhereNew: 'Un nouvel endroit',
      plannedLocation: 'Lieu prévu',
      townOrNeighbourhood: 'Ville ou quartier',
      farmName: 'Nom de la ferme',
      whereFarm: 'Où se trouve votre ferme?',
      townOrCounty: 'Ville ou comté',
      produceTypes: 'Quels types de produits vendez-vous?',
      pounds: 'Combien de livres avez-vous de disponibles toutes les deux semaines?',
      orgName: 'Nom de votre organisme ou de votre espace',
      spaceAddress: 'Adresse de votre espace',
      alreadyHost: 'Accueillez-vous déjà un lieu Square Roots?',
      newLocation: 'Non, ce serait un nouveau lieu',
      yesSite: (site) => `Oui : ${site}`,
      message: 'Message',
      optional: 'Facultatif',
      loginLegend: 'Votre connexion au portail des partenaires',
      username: 'Nom d’utilisateur',
      password: 'Mot de passe',
      passwordHint: 'Au moins 8 caractères, et pas seulement des chiffres',
      review: 'Nous examinerons votre demande et vous écrirons une fois votre compte approuvé. Vous avez déjà un compte? ',
      howWeUse: '. Comment nous utilisons vos renseignements : ',
    },
    requestLocation: {
      title: 'Square Roots dans votre région',
      lead: 'Pas encore de lieu près de chez vous? Dites-nous où vous êtes. Quand assez de gens le demandent, nous cherchons quelqu’un pour en lancer un.',
      thanks: (area) =>
        `Merci! Nous avons ajouté ${area} à la liste et nous vous écrirons si un lieu ouvre près de chez vous. `,
      couldHelpThanks: 'Comme vous avez dit pouvoir aider, un membre de l’équipe communiquera avec vous. ',
      seeLocations: 'Voir les lieux actuels',
      postalCode: 'Code postal',
      postalHint: '(ou seulement la première partie, comme B3H)',
      town: 'Ville ou quartier',
      email: 'Courriel',
      emailHint: '(pour vous prévenir si un lieu ouvre)',
      couldHelp: 'Je pourrais aider à gérer ou à accueillir un lieu',
      couldHelpHint:
        ' Les gestionnaires communautaires organisent des distributions toutes les deux semaines, avec le soutien de notre équipe.',
      anythingElse: 'Autre chose?',
      ask: 'Demander un lieu',
      keepOnly: 'Nous gardons votre courriel et votre code postal seulement à cette fin.',
    },
    privacyPage: {
      title: 'Confidentialité',
      lead: 'Ce que nous recueillons, pourquoi, qui y a accès et combien de temps nous le gardons.',
      draft:
        'Ceci est une ébauche que Square Roots doit examiner avant que le site soit utilisé par le public, idéalement avec les conseils d’une personne qui connaît la loi canadienne sur la protection des renseignements personnels (LPRPDE).',
      whoTitle: 'Qui nous sommes',
      who: 'Square Roots est une entreprise d’intérêt communautaire gérée par des étudiants d’Enactus Saint Mary’s, à l’Université Saint Mary’s à Halifax. Pour toute question sur vos renseignements, écrivez à ',
      reserveTitle: 'Quand vous réservez un panier',
      weAsk: 'Nous vous demandons :',
      askName: 'votre nom, pour que votre gestionnaire communautaire sache à qui est le panier;',
      askContact:
        'un courriel ou un numéro de téléphone, pour vous envoyer votre confirmation et vous prévenir en cas de changement;',
      askAddress: 'votre adresse, seulement si vous demandez la livraison à domicile.',
      alsoKeep:
        'Nous gardons aussi le nombre de paniers réservés, le prix choisi et tout don ajouté. Le prix que vous choisissez reste confidentiel : seuls votre gestionnaire communautaire et l’équipe de Square Roots le voient.',
      whoSeesLabel: 'Qui y a accès :',
      whoSees:
        ' le gestionnaire communautaire de votre lieu et l’équipe de Square Roots. Pour la livraison à domicile, le partenaire de livraison (par exemple BayRides) reçoit votre nom, votre adresse et votre numéro de téléphone. Si un site d’accueil a réservé pour vous, il voit le nom donné et votre code de cueillette. Nous ne vendons jamais vos renseignements et ne les utilisons jamais à des fins publicitaires.',
      howLongLabel: 'Combien de temps :',
      howLong:
        ' nous supprimons votre nom et vos coordonnées 60 jours après votre distribution. Si vous annulez, ils sont supprimés tout de suite. Si vous nous avez demandé de réserver à chaque distribution, nous les gardons jusqu’à ce que vous arrêtiez.',
      emailsTitle: 'Les courriels que nous envoyons',
      emails:
        'Seulement au sujet de vos réservations : votre confirmation, des rappels avant votre distribution, une courte question après coup sur votre panier, et des avis si votre distribution change. Il n’y a pas de liste d’envoi.',
      areaTitle: '« Square Roots dans ma région »',
      area: 'Si vous nous demandez de lancer un lieu près de chez vous, nous gardons votre courriel et votre code postal pour vous prévenir si un lieu ouvre, et pour montrer à l’équipe où les gens en demandent. Vous pouvez nous demander de les supprimer à tout moment.',
      contactTitle: 'Messages envoyés par la page Nous joindre',
      contact: 'Nous gardons les messages envoyés par la page Nous joindre pendant un an, puis nous les supprimons.',
      accountsTitle: 'Comptes du portail des partenaires',
      accounts:
        'Les gestionnaires communautaires, les fermes et les sites d’accueil ont un compte avec leur nom, leur courriel, leur téléphone et leur organisme. Ces renseignements sont gardés tant qu’ils travaillent avec Square Roots. Demandez-nous de fermer votre compte et nous le supprimerons.',
      cookiesTitle: 'Témoins et votre appareil',
      cookies:
        'Le portail des partenaires utilise un seul témoin pour garder votre session ouverte. Si vous cochez « Mémoriser mes coordonnées » en réservant, votre nom et vos coordonnées sont enregistrés sur votre propre appareil (pas sur nos serveurs) pour vous éviter de les retaper. Le site n’utilise aucun témoin de suivi ou publicitaire.',
      choicesTitle: 'Vos choix',
      choices:
        'Vous pouvez consulter, corriger ou supprimer vos renseignements à tout moment : modifiez ou annulez une réservation avec le lien de votre courriel de confirmation, ou écrivez à ',
      choicesEnd: ' et nous vous aiderons dans les 30 jours.',
      back: 'Retour à la réservation d’un panier',
    },
    login: {
      title: 'Portail des partenaires',
      lead: 'Pour les gestionnaires communautaires, les fermes, les sites d’accueil et l’équipe de Square Roots.',
      sessionEnded: 'Vous avez été déconnecté après un moment d’inactivité. Veuillez vous reconnecter.',
      username: 'Nom d’utilisateur',
      password: 'Mot de passe',
      code: 'Code à 6 chiffres',
      codeHint: '(de votre application d’authentification)',
      loggingIn: 'Connexion…',
      logIn: 'Se connecter',
      forgot: 'Mot de passe oublié?',
      newHere: 'Nouveau chez Square Roots? ',
      signUp: 'Inscrivez-vous comme partenaire',
      sideTitle: 'Réduire le gaspillage alimentaire, accroître la sécurité alimentaire',
      sideText:
        'Square Roots offre à des membres de la communauté partout en Nouvelle-Écosse des produits parfaitement sains qui ne répondent pas aux normes esthétiques des épiceries.',
      demoTitle: 'Comptes de démonstration',
      demoMode: 'Mode démonstration.',
      demoNote:
        ' Ces comptes et leurs données sont fictifs. Cette liste disparaît quand le mode démonstration est désactivé.',
      demoTap: 'Touchez un compte pour remplir le formulaire. Le mot de passe de chaque compte de démonstration est ',
      demoPending: 'Inscrits, en attente d’approbation',
      demoPendingNote: 'Ces personnes se sont inscrites sur le site. Connectez-vous avec l’un de ces comptes pour voir ce qu’elles voient.',
    },
    pending: {
      declinedTitle: 'Au sujet de votre demande',
      thanks: (name) => `Merci, ${name}!`,
      declined:
        'Nous ne pouvons pas approuver votre demande pour le moment. Pour toute question, écrivez-nous à squareroots@enactussmu.ca.',
      received: (role) => `Nous avons bien reçu votre demande pour vous joindre à Square Roots (${role}).`,
      nextTitle: 'Les prochaines étapes',
      next1: 'Un membre de l’équipe de Square Roots d’Enactus Saint Mary’s examine votre demande.',
      next2: 'Nous vous écrirons une fois votre compte approuvé. Cela prend habituellement quelques jours.',
      next3:
        'Connectez-vous ensuite ici avec le nom d’utilisateur et le mot de passe choisis : votre portail des partenaires sera prêt.',
      back: 'Retour au site de Square Roots',
      logOut: 'Se déconnecter',
    },
    forgot: {
      title: 'Mot de passe oublié?',
      lead: 'Entrez l’adresse courriel de votre compte du portail des partenaires et nous vous enverrons un lien pour en choisir un nouveau.',
      enterEmail: 'Entrez l’adresse courriel de votre compte.',
      linkOnce:
        'Le lien fonctionne une seule fois. Le courriel vous rappelle aussi votre nom d’utilisateur. Si rien n’arrive d’ici quelques minutes, vérifiez vos courriels indésirables ou écrivez-nous à ',
      backToLogin: 'Retour à la connexion',
      emailMe: 'M’envoyer un lien',
    },
    reset: {
      title: 'Choisir un nouveau mot de passe',
      noMatch: 'Les deux mots de passe ne correspondent pas.',
      changed: 'Votre mot de passe est changé. Vous pouvez maintenant vous connecter avec le nom d’utilisateur ',
      logIn: 'Se connecter',
      newLink: 'Obtenir un nouveau lien',
      newPassword: 'Nouveau mot de passe',
      passwordHint: '(au moins 8 caractères, et pas seulement des chiffres)',
      again: 'Retapez-le',
      saving: 'Enregistrement…',
      save: 'Enregistrer le nouveau mot de passe',
    },
    notFound: {
      title: 'Page introuvable',
      text: 'Nous n’avons pas trouvé cette page. Elle a peut-être été déplacée, ou le lien contient une erreur.',
      home: 'Aller à l’accueil',
      findDrop: 'Trouver une distribution près de chez vous',
      portal: 'Portail des partenaires',
    },
    crash: {
      title: 'Un problème est survenu',
      sorry: 'Désolés, cette page ne s’est pas chargée correctement.',
      tryAgain:
        'Essayez de recharger la page. Si le problème persiste, écrivez-nous à squareroots@enactussmu.ca.',
      reload: 'Recharger la page',
      home: 'Aller à l’accueil',
    },
  },
}
