# Generated by Django 6.1.1 on 2026-09-23 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drops', '0002_dropcycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('location', models.CharField(blank=True, help_text='Town or county, e.g. Canard, Kings County', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FarmOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_at', models.DateTimeField()),
                ('pickup_notes', models.CharField(blank=True, help_text='e.g. Square Roots van at the farm stand', max_length=300)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for farm'), ('confirmed', 'Confirmed'), ('cant_fill', "Farm can't fill")], default='waiting', max_length=16)),
                ('farm_note', models.CharField(blank=True, help_text="The farm's reason if it can't fill the order.", max_length=500)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.CharField(choices=[('not_paid', 'Not paid yet'), ('paid', 'Paid')], default='not_paid', max_length=16)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('drop_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farm_orders', to='drops.dropcycle')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='farms.farm')),
            ],
            options={
                'ordering': ['pickup_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce', models.CharField(max_length=100)),
                ('pounds', models.PositiveIntegerField()),
                ('price_per_pound', models.DecimalField(decimal_places=2, max_digits=6)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='farms.farmorder')),
            ],
        ),
        migrations.CreateModel(
            name='ProduceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce', models.CharField(help_text='e.g. Carrots', max_length=100)),
                ('pounds', models.PositiveIntegerField()),
                ('price_per_pound', models.DecimalField(decimal_places=2, max_digits=6)),
                ('available_until', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='farms.farm')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
