# Generated by Django 6.1.1 on 2026-09-23 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='pickup_notes',
            field=models.CharField(blank=True, help_text='Copied onto each new order from this farm.', max_length=300),
        ),
        migrations.AddField(
            model_name='farmorderline',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='farms.producelisting'),
        ),
    ]
