# Generated by Django 6.1.1 on 2026-09-23 02:54

from django.db import migrations, models


def mark_existing_orders_sent(apps, schema_editor):
    # Orders made before drafts existed were already visible to farms, so they count as sent.
    FarmOrder = apps.get_model("farms", "FarmOrder")
    for order in FarmOrder.objects.filter(sent_at__isnull=True):
        order.sent_at = order.responded_at or order.pickup_at
        order.save(update_fields=["sent_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_farm_pickup_notes_farmorderline_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmorder',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_orders_sent, migrations.RunPython.noop),
    ]
