# Generated by Django 6.1.1 on 2026-10-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_farmorder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='kind',
            field=models.CharField(choices=[('farm', 'Farm'), ('wholesaler', 'Wholesaler')], default='farm', max_length=16),
        ),
    ]
