# Generated by Django 6.1.1 on 2026-10-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_routes_and_drop_off_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
